services:
  web:
    container_name: "csvimporter"
    build: .
    volumes:
      - /media/data/NPD:/data
    depends_on:
      db:
        condition: service_healthy
      
  db:
    image: postgres
    restart: always
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: npd

    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

